services:
  monitor:
    build: .
    ports:
      - "8088:8088"
    environment:
      FETCH_INTERVAL_MINUTES: 5  # Fetching interval in minutes
      SESSION_REFRESH_INTERVAL_MINUTES: 30  # Refreshing session interval in minutes
      TELEGRAM_TOKEN: "YourTelegramBotToken"  # Telegram bot token
    restart: unless-stopped